steps:
  # Build the image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-west4-docker.pkg.dev/cc-project-490314/cloud-run-source-deploy/weather-cc-project:$COMMIT_SHA",
        ".",
      ]
  # Push the image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "europe-west4-docker.pkg.dev/cc-project-490314/cloud-run-source-deploy/weather-cc-project:$COMMIT_SHA",
      ]
  # Deploy image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "weather-cc-project"
      - "--image"
      - "europe-west4-docker.pkg.dev/cc-project-490314/cloud-run-source-deploy/weather-cc-project:$COMMIT_SHA""
      - "--region"
      - "europe-west4"
images:
  - "europe-west4-docker.pkg.dev/cc-project-490314/cloud-run-source-deploy/weather-cc-project:$COMMIT_SHA"
